In [4]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

log = pd.read_csv("G:\data\datasets\logogo.csv")

ModuleNotFoundError: No module named 'pandas'

In [8]:
log.head(10)

statusId  accelerate      X      Y      Z
0         6           1 -0.268  0.536  9.785
1         6           1 -0.268  0.536  9.785
2         6           1 -0.268  0.536  9.785
3         6           1 -0.268  0.536  9.785
4         6           1 -0.268  0.536  9.785
5         6           1 -0.268  0.536  9.785
6         6           1 -0.268  0.536  9.785
7         6           1 -0.268  0.536  9.785
8         6           1 -0.268  0.536  9.785
9         6           1 -0.268  0.536  9.785

In [9]:
log.tail(10)

statusId  accelerate      X      Y      Z
273551         8           1 -6.972  5.784  7.475
273552         8           1 -7.431  5.516  7.268
273553         8           1 -7.661  5.439  7.268
273554         8           1 -7.393  5.324  6.969
273555         8           1 -6.512  5.133  6.969
273556         8           1 -5.286  5.171  6.767
273557         8           1 -3.792  5.286  6.767
273558         8           1 -2.260  5.324  7.002
273559         8           1 -1.187  5.554  7.002
273560         8           1 -0.421  5.631  8.096

In [10]:
log.shape

(273561, 5)

In [11]:
x = log.drop('statusId', axis =1)
y = log['statusId']
z = x.drop('accelerate', axis = 1)

In [12]:
z.head(10)

X      Y      Z
0 -0.268  0.536  9.785
1 -0.268  0.536  9.785
2 -0.268  0.536  9.785
3 -0.268  0.536  9.785
4 -0.268  0.536  9.785
5 -0.268  0.536  9.785
6 -0.268  0.536  9.785
7 -0.268  0.536  9.785
8 -0.268  0.536  9.785
9 -0.268  0.536  9.785

In [13]:
from sklearn.model_selection import train_test_split
y_train, y_test, z_train, z_test = train_test_split(y,z, test_size = 0.2)

In [14]:
y_train.head(10)

62719     6
167479    7
17978     6
147614    7
45128     6
196179    8
238113    8
23837     6
28763     6
3929      6
Name: statusId, dtype: int64

In [15]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(z_train, y_train)

DecisionTreeClassifier()

In [16]:
y_pred = classifier.predict(z_test)

In [17]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[18011     0     0]
 [    0 16790  1167]
 [    0  1224 17521]]
              precision    recall  f1-score   support

           6       1.00      1.00      1.00     18011
           7       0.93      0.94      0.93     17957
           8       0.94      0.93      0.94     18745

    accuracy                           0.96     54713
   macro avg       0.96      0.96      0.96     54713
weighted avg       0.96      0.96      0.96     54713



In [18]:
confusion_matrix?

Signature:
confusion_matrix(
    y_true,
    y_pred,
    *,
    labels=None,
    sample_weight=None,
    normalize=None,
)
Docstring:
Compute confusion matrix to evaluate the accuracy of a classification.

By definition a confusion matrix :math:`C` is such that :math:`C_{i, j}`
is equal to the number of observations known to be in group :math:`i` and
predicted to be in group :math:`j`.

Thus in binary classification, the count of true negatives is
:math:`C_{0,0}`, false negatives is :math:`C_{1,0}`, true positives is
:math:`C_{1,1}` and false positives is :math:`C_{0,1}`.

Read more in the :ref:`User Guide <confusion_matrix>`.

Parameters
----------
y_true : array-like of shape (n_samples,)
    Ground truth (correct) target values.

y_pred : array-like of shape (n_samples,)
    Estimated targets as returned by a classifier.

labels : array-like of shape (n_classes), default=None
    List of labels to index the matrix. This may be used to reorder
    or select a subset of labels.
    If

In [19]:
pandas?

Object `pandas` not found.


In [20]:
sklearn?

Object `sklearn` not found.


In [21]:
pd.Dataframe?

Object `pd.Dataframe` not found.
